<a href="https://colab.research.google.com/github/Sarweshchopade/training_ANP/blob/main/Numpy%2C1d%2C2d.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Write a program to create a 1D NumPy array with five elements entered by the user.

-->

In [1]:
import numpy as np
elements=[]
for i in range(5):
    value=int(input(f"Enter element {i+1}: "))
    elements.append(value)
arr=np.array(elements)
print("1D NumPy Array:", arr)

Enter element 1: 2
Enter element 2: 3
Enter element 3: 6
Enter element 4: 9
Enter element 5: 24
1D NumPy Array: [ 2  3  6  9 24]


Write a program to find the length of a 1D NumPy array.

-->

In [2]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print("Length of array:", len(arr))

Length of array: 5


Write a program to access the first, middle, and last element of a NumPy array.

-->

In [3]:
import numpy as np
arr=np.array([10, 20, 30, 40, 50])
print("First element:", arr[0])
print("Middle element:", arr[len(arr)//2])
print("Last element:", arr[-1])

First element: 10
Middle element: 30
Last element: 50


Write a program to slice a NumPy array from index 2 to 5.

-->

In [4]:
import numpy as np
arr=np.array([10, 20, 30, 40, 50, 60, 70])
print("Sliced array:", arr[2:6])

Sliced array: [30 40 50 60]


Write a program to print all elements of a NumPy array using a loop.

-->

In [5]:
import numpy as np
arr=np.array([10, 20, 30, 40, 50])
for i in arr:
    print(i)

10
20
30
40
50


Write a program to add 10 to each element of a NumPy array.

-->

In [6]:
import numpy as np
arr=np.array([10, 20, 30, 40, 50])
new_arr=arr+10
print("Updated array:", new_arr)

Updated array: [20 30 40 50 60]


Write a program to find the sum and average of elements in a 1D NumPy array.

-->

In [7]:
import numpy as np
arr=np.array([10, 20, 30, 40, 50])
print("Sum:", np.sum(arr))
print("Average:", np.mean(arr))

Sum: 150
Average: 30.0


Write a program to find the maximum and minimum value in a NumPy array.

-->

In [8]:
import numpy as np
arr=np.array([10, 5, 30, 25, 15])
print("Maximum value:", np.max(arr))
print("Minimum value:", np.min(arr))

Maximum value: 30
Minimum value: 5


Write a program to reverse a NumPy array using slicing.

-->

In [9]:
import numpy as np
arr=np.array([10, 20, 30, 40, 50])
print("Reversed array:", arr[::-1])

Reversed array: [50 40 30 20 10]


Write a program to check whether a specific element exists in a NumPy array.

-->

In [10]:
import numpy as np
arr=np.array([10, 20, 30, 40, 50])
element=30
if element in arr:
    print("Element exists in the array")
else:
    print("Element does not exist in the array")

Element exists in the array


Write a program to create a 2D NumPy array of size 3x3 and display it.

-->

In [11]:
import numpy as np
arr=np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Write a program to find the shape of a 2D NumPy array.

-->

In [12]:
import numpy as np
arr=np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print("Shape of array:", arr.shape)

Shape of array: (3, 3)


Write a program to access a specific element from a 2D array using row and column index.

-->

In [13]:
import numpy as np
arr=np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print("Element at row 1, column 2:", arr[1, 2])

Element at row 1, column 2: 6


Write a program to extract the first row and first column from a 2D NumPy array.

-->

In [14]:
import numpy as np
arr=np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print("First row:", arr[0, :])
print("First column:", arr[:, 0])

First row: [1 2 3]
First column: [1 4 7]


Write a program to slice a 2D NumPy array to get a sub-matrix.

-->

In [15]:
import numpy as np
arr=np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
sub_matrix=arr[0:2, 1:3]
print("Sub-matrix:\n", sub_matrix)

Sub-matrix:
 [[2 3]
 [5 6]]


Write a program to calculate the sum of all elements in a 2D NumPy array.

-->

In [16]:
import numpy as np
arr=np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print("Sum of all elements:", np.sum(arr))

Sum of all elements: 45


Write a program to calculate row-wise sum of a 2D NumPy array.

-->

In [17]:
import numpy as np
arr=np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print("Row-wise sum:", np.sum(arr, axis=1))

Row-wise sum: [ 6 15 24]


Write a program to calculate column-wise average of a 2D NumPy array.

-->

In [18]:
import numpy as np
arr=np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print("Column-wise average:", np.mean(arr, axis=0))

Column-wise average: [4. 5. 6.]


Write a program to multiply each element of a 2D NumPy array by 2.

-->

In [19]:
import numpy as np
arr=np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print("Array after multiplication:\n", arr * 2)

Array after multiplication:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


Write a program to find the maximum value from each row of a 2D NumPy array.

-->

In [20]:
import numpy as np
arr=np.array([[1, 2, 3],
                [9, 5, 6],
                [7, 8, 4]])
print("Maximum from each row:", np.max(arr, axis=1))

Maximum from each row: [3 9 8]
